# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171012_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_picture/none/no_image_user.png', upload_to='profile_picture/'),
        ),
    ]
