# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20170928_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unit', to=settings.AUTH_USER_MODEL),
        ),
    ]
