# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:41
from __future__ import unicode_literals
from django.db import models, migrations


def load_units(apps, schema_editor):
    Units = apps.get_model('units', 'unit')
    units_data = Units(id=1, User=1, name='Kilogram', print_name='KG')
    units_data.save()


class Migration(migrations.Migration):
    dependencies = [
        ('units', '0005_auto_20170928_1439'),
    ]

    operations = [
        migrations.RunPython(load_units)
    ]