# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171001_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.CharField(max_length=32),
        ),
    ]
