# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('transactions', '0005_auto_20171002_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='customers.Customer'),
            preserve_default=False,
        ),
    ]
