# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20171013_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_hour',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
