# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20171014_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='valid_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
