# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20171013_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('name', 'phone_number')]),
        ),
    ]
